<?php

declare(strict_types=1);
/**
 * Repository for AI-generated plugin records.
 *
 * Extracted from SdAiAgent\Core\Database to keep domain logic focused.
 * Database::* methods delegate here for backward compatibility.
 *
 * @package SdAiAgent
 * @license GPL-2.0-or-later
 */

namespace SdAiAgent\Repositories;

use SdAiAgent\Core\Database;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles persistence for plugins generated by the AI plugin-builder.
 */
class GeneratedPluginsRepository {

	/**
	 * Insert a new generated plugin record.
	 *
	 * @param array<string, mixed> $data Plugin data: slug, description, plan, plugin_file, files, status, sandbox_result, activation_error.
	 * @return int|false Inserted row ID or false on failure.
	 */
	public static function insert( array $data ): int|false {
		global $wpdb;
		/** @var \wpdb $wpdb */

		$now = current_time( 'mysql', true );
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery -- Custom table insert; caching not applicable.
		$result = $wpdb->insert(
			Database::generated_plugins_table_name(),
			[
				'slug'             => $data['slug'] ?? '',
				'description'      => $data['description'] ?? '',
				'plan'             => $data['plan'] ?? '',
				'plugin_file'      => $data['plugin_file'] ?? '',
				'files'            => $data['files'] ?? '[]',
				'status'           => $data['status'] ?? 'installed',
				'sandbox_result'   => $data['sandbox_result'] ?? '',
				'activation_error' => $data['activation_error'] ?? '',
				'created_at'       => $data['created_at'] ?? $now,
				'updated_at'       => $data['updated_at'] ?? $now,
			],
			[ '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s', '%s' ]
		);

		return $result ? (int) $wpdb->insert_id : false;
	}

	/**
	 * Update fields for a generated plugin record by slug.
	 *
	 * @param string               $slug Plugin slug.
	 * @param array<string, mixed> $data Fields to update.
	 * @return bool Whether the update succeeded.
	 */
	public static function update( string $slug, array $data ): bool {
		global $wpdb;
		/** @var \wpdb $wpdb */

		$data['updated_at'] = current_time( 'mysql', true );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table update; caching not applicable.
		$result = $wpdb->update(
			Database::generated_plugins_table_name(),
			$data,
			[ 'slug' => $slug ],
			null,
			[ '%s' ]
		);

		return $result !== false;
	}

	/**
	 * Get a single generated plugin record by slug.
	 *
	 * @param string $slug Plugin slug.
	 * @return object|null Plugin row or null.
	 */
	public static function get( string $slug ): ?object {
		global $wpdb;
		/** @var \wpdb $wpdb */

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table query; caching not applicable.
		return $wpdb->get_row(
			$wpdb->prepare(
				'SELECT * FROM %i WHERE slug = %s',
				Database::generated_plugins_table_name(),
				$slug
			)
		);
	}

	/**
	 * List generated plugin records, optionally filtered by status.
	 *
	 * @param string $status Filter by status (e.g. 'installed', 'active'). Empty string = all.
	 * @return list<object>
	 */
	public static function list( string $status = '' ): array {
		global $wpdb;
		/** @var \wpdb $wpdb */

		$table = Database::generated_plugins_table_name();

		if ( '' !== $status ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table query; caching not applicable.
			$rows = $wpdb->get_results(
				$wpdb->prepare(
					'SELECT * FROM %i WHERE status = %s ORDER BY created_at DESC',
					$table,
					$status
				)
			);
		} else {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table query; caching not applicable.
			$rows = $wpdb->get_results(
				$wpdb->prepare(
					'SELECT * FROM %i ORDER BY created_at DESC',
					$table
				)
			);
		}

		return $rows ?? [];
	}

	/**
	 * Update the status of a generated plugin by slug.
	 *
	 * @param string $slug   Plugin slug.
	 * @param string $status New status value (e.g. 'installed', 'active', 'error').
	 * @return bool Whether the update succeeded.
	 */
	public static function update_status( string $slug, string $status ): bool {
		return self::update( $slug, [ 'status' => $status ] );
	}

	/**
	 * Delete a generated plugin record by slug.
	 *
	 * @param string $slug Plugin slug.
	 * @return bool Whether the delete succeeded.
	 */
	public static function delete( string $slug ): bool {
		global $wpdb;
		/** @var \wpdb $wpdb */

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table delete; caching not applicable.
		$result = $wpdb->delete(
			Database::generated_plugins_table_name(),
			[ 'slug' => $slug ],
			[ '%s' ]
		);

		return $result !== false;
	}
}
